META:
  NAME : NTU_ttspcc2_833        #folder name to store trained model and results

MODEL:
  MODEL_TYPE : ttspcc2   #type of model to train, temporal, temporal_2, temporal_3, temporal_4, spatial-temporal or parts
  EMBED_DIM : 32           #embedding dimension used by the model
  SEGMENT_LEN : 24          #length of sliding window (no.of frames)
  DEBUG : FALSE              #load subset of trajectories in debug mode
  DATASET : NTU_2D          #dataset used HR-Crime/UTK/NTU_2D/NTU_3D

DECOMPOSED:
  ENABLE: FALSE                #whether to use globally and locally decomposed trajectories
  TYPE: GS                    #possible values: GR (Global repeated), GS (Global single)

TUBELET:                    #whether to use tubelet embeddings or not
  ENABLE: TRUE            
  KERNEL: 8,3,3          #Kernel+Stride for tubelet embeddings
  STRIDE: 8,3,3
  PAD_MODE: constant      #Could be constant, replicate, reflect

VIS:
  TYPE : SKEL # ATTN/SKEL
  # TEST_SAMPLE : Abuse050_0034
  # TEST_INDEX : 1000
  # TEST_INDEX : 1649
  # TEST_SAMPLE : S032C002P043R001A097_0
  # TEST_INDEX : 20
  TEST_SAMPLE : S001C003P005R002A059_0
  TEST_INDEX : 20