META:
  NAME : temporal_1_kayleigh_500_c_4_new_4

MODEL:
  MODEL_TYPE : temporal   #type of model to train, temporal, temporal_2, temporal_3, temporal_4, spatial-temporal or parts
  EMBED_DIM : 256           #embedding dimension used by the model
  SEGMENT_LEN : 24          #length of sliding window
  DEBUG : FALSE              #load subset of trajectories in debug mode
  DATASET : NTU_2D          #dataset used HR-Crime/UTK/NTU_2D/NTU_3D


TRAINING:
  EPOCHS : 100              #maximum number of epochs during training
  BATCH_SIZE : 200         #batch size for training
  PATIENCE : 3             #patience before early stopping is enabled
  LR : 0.001                #starting learning rate for adaptive learning
  LR_PATIENCE : 3           #patience before learning rate is decreased
  KFOLD: 3                  #number of folds used for cross-validation