META:
  NAME : tubelet_test_NTU_2D_epochs_100_522

MODEL:
  MODEL_TYPE : temporal   #type of model to train, temporal, temporal_2, temporal_3, temporal_4, spatial-temporal or parts
  EMBED_DIM : 256           #embedding dimension used by the model
  SEGMENT_LEN : 24          #length of sliding window
  DEBUG : FALSE              #load subset of trajectories in debug mode
  DATASET : NTU_2D          #dataset used HR-Crime/UTK/NTU_2D/NTU_3D
  DECOMPOSED : FALSE         #whether to use globally and locally decomposed trajectories
  TUBELET : TRUE            #whether to use tubelet embeddings or not


TRAINING:
  EPOCHS : 100              #maximum number of epochs during training
  BATCH_SIZE : 1000         #batch size for training
  PATIENCE : 2             #patience before early stopping is enabled
  LR : 0.001                #starting learning rate for adaptive learning
  LR_PATIENCE : 3           #patience before learning rate is decreased
  KFOLD: 3                  #number of folds used for cross-validation